name: .NET Desktop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Lab1/   # 👈 adjust if needed

    env:
      Solution_Name: Lab1.sln
      Test_Project_Path_1: Lab1Test.UnitTests/Lab1Test.UnitTests.csproj
      Test_Project_Path_2: SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x   # or your project version

      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build
        run: dotnet build ${{ env.Solution_Name }} --no-restore

      - name: NUnit Tests
        run: dotnet test ${{ env.Test_Project_Path_1 }} --no-build --verbosity normal

      - name: SpecFlow Tests
        run: dotnet test ${{ env.Test_Project_Path_2 }} --no-build --verbosity normal
